@startuml
'https://plantuml.com/class-diagram

interface ScoreDao{
    + getScoresFromFile():void
    + printScoreDatas():void
    + sortByScore():void
    + doAdd(ScoreData scoredata):void
    + doDelete((ScoreData scoredata):void

}
class  ScoreDaoImp{

    - fileName:String
    - scoreDatas:List<ScoreData>
    + ScoreDaoImp(String fileName)

    + getScoresFromFile():void
    + printScoreDatas():void
    + sortByScore():void
    + doAdd(ScoreData scoredata):void
    + doDelete((ScoreData scoredata):void

}
class ScoreData{
    - name:String
    - score:int
    - date:String
    + ScoreData(String name, int score, String date)
    + setName(String name):void
    + setScore(int score):void
    + setDate(String date):void
    + getName():String
    + getScore():int
    + getDate():String

}

ScoreDaoImp ..|> ScoreDao

ScoreDaoImp --> ScoreData

@enduml